services:
  frontend:
    build:
      context: .
      target: build
    command: ["npm", "run", "build"]
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3000:5173"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      target: base
    command: ["bash", "start.sh"]
    env_file: ".env"
    environment:
      - ENV=prod
      - WEBUI_AUTH=True
      - ENABLE_OLLAMA_API=false
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8080:8080'
    restart: always
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - backend/data
        - action: rebuild
          path: backend/requirements.txt
    networks:
      - app-network

volumes:
  open-webui:

networks:
  app-network:
    external: true
    driver: bridge
